openapi: "3.0.1"
info:
  title: "Invedent"
paths:
  /:
    post:
      responses:
        default:
          description: "EventBridge response"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"
        credentials:
          Fn::GetAtt: [InvedentHttpApiRole, Arn]
        requestParameters:
          Detail: "$request.body.Detail"
          DetailType: inventory
          Source: custom.inventoryManager
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"